apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-app-port
  selector:
    app: web-app
